# Generated by Django 3.0.3 on 2020-03-26 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_auto_20200326_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FaceCapture',
        ),
    ]
