# Generated by Django 3.0.3 on 2020-03-26 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('captures', '0003_auto_20200326_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImageCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        )
    ]
