# Generated by Django 3.0.3 on 2020-03-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('captures', '0005_auto_20200326_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimagecapture',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
            preserve_default=False,
        ),
    ]
