# Generated by Django 3.0.3 on 2020-03-30 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0007_auto_20200330_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceimageattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='faceimageattempt',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captures.CapturePack'),
        ),
        migrations.AddField(
            model_name='faceimagecapture',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='captures.CapturePack'),
        )
    ]
