# Generated by Django 3.0.3 on 2020-03-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('captures', '0008_auto_20200330_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturepack',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
