# Generated by Django 3.0.3 on 2020-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0011_auto_20200331_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturepack',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
