# Generated by Django 3.0.3 on 2020-03-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0012_auto_20200331_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimageattempt',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='captures.CapturePack'),
        ),
    ]
