# Generated by Django 3.0.3 on 2020-03-31 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('captures', '0013_auto_20200331_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturepack',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
