# Generated by Django 3.0.3 on 2020-04-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0014_auto_20200331_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceimageattempt',
            name='pack',
        ),
    ]
