# Generated by Django 3.0.3 on 2020-04-03 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0015_auto_20200401_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturepack',
            name='path',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='faceimagecapture',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='captures.CapturePack'),
        ),
    ]
