# Generated by Django 3.0.3 on 2020-03-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=30)),
                ('confidence', models.FloatField()),
                ('date', models.DateTimeField()),
                ('recognized', models.BooleanField()),
                ('origin', models.CharField(max_length=20)),
                ('face_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognitor.FaceImage')),
            ],
        ),
    ]
