# Generated by Django 3.0.3 on 2020-03-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognitor', '0002_faceimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionattempt',
            name='face_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recognitor.FaceImage'),
        ),
    ]
