# Generated by Django 3.0.3 on 2020-03-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('recognitor', '0003_auto_20200320_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='recognitionattempt',
            name='face_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recognitor.FaceImage'),
            preserve_default=False,
        ),
    ]
