# Generated by Django 3.0.3 on 2020-03-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captures', '0002_auto_20200326_1053'),
        ('recognitor', '0005_auto_20200320_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionattempt',
            name='face_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captures.FaceImage'),
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
