# Generated by Django 3.0.3 on 2020-03-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitor', '0006_auto_20200326_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitionattempt',
            name='face_image',
        ),
    ]
