# Generated by Django 3.0.3 on 2020-03-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognitor', '0007_remove_recognitionattempt_face_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecognitionAttempt',
        ),
    ]
